### PR TITLE
Tooltip: fix CSS top calculation for error message

### PR DESCRIPTION
**Pull request by andyroo2000**
@mikesherov @mrjoelkemp 
cc: @be-dmitry 

Partially fixes adobe-community/issues#2827

Applying negative `top` in the amount of the `outerHeight` of the `$tooltip` was causing the error messages to appear in unpredictable places relative to the form field.

Instead, using the `outerHeight` of the `$context` produces the desired result.

*Here is the before:*

image

*And here is after my change:*

image

---

Note that the display of multiple messages mentioned in the Gissue has been solved locally and is going to be part of a separate PR on be.net. This PR is only to fix the positioning.

### CODE REVIEW

**Comment by mikesherov** [comment]
I'm not comfortable with this change because it's fixing a style issues from *two* style upgrades ago, when we have a new one coming right around the corner.

@andyroo2000 I appreciate the effort here, but perhaps we should close as wontfix.

**Comment by andyroo2000** [comment]
@mikesherov 

:cry:

Okay, I guess that makes sense... Just want to make sure, as it's not just about moving it up or down as it is calculating the amount that it moves up or down from the correct element... Seems like that would be a good starting point if tooltip is used in future designs, but maybe tooltip won't be used in the redesign?

My feelings won't be hurt if code doesn't make it in, just putting that out there... in case it saves someone else the time of figuring that out again (if it is actually used in the future).

But say the word and I'll close it and not worry about it.  :)

**Comment by mikesherov** [comment]
We'll likely throw away tooltip. It's in a deprecated repo with seriously out of date code.

**Comment by andyroo2000** [comment]
Ah, TIL! I won't lose sleep over it then.

**Pull request closed without merging**
